#!/usr/bin/env bash
# Opengrep -- alternative tool, branch PY-072 (Python 3.8, poetry-core / conda).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "opengrep" "" ""
require_binary "opengrep" "opengrep"
require_import "opengrep" "" ""


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
opengrep scan --config "Tool Triggering (Synthetic Data)/opengrep/rules.yaml" --json -o reports/opengrep.json "$SRC"
rc=$?
accept_findings "opengrep" "$rc" "reports/opengrep.json"
exit $?
