#!/usr/bin/env bash
# Bandit -- primary tool, branch PY-005 (Python 3.6, setuptools / uv).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="src"
PKG="orderlab"

require_python_floor "bandit" ">=3.10" "bandit==1.9.4"
require_import "bandit" "bandit" "bandit==1.9.4"

mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
"$PYBIN" -m bandit -r "$SRC" -f json -o reports/bandit-only.json -ll
rc=$?
accept_findings "bandit" "$rc" "reports/bandit-only.json"
exit $?
