#!/usr/bin/env bash
# Bandit -- primary tool, branch PY-180 (Python 3.13, uv_build / poetry).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "bandit" ">=3.10" "bandit==1.9.4"
require_import "bandit" "bandit" "bandit==1.9.4"
require_smoke "bandit" "bandit==1.9.4" "$PYBIN" -m bandit --version


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
"$PYBIN" -m bandit -r "$SRC" -f json -o reports/bandit-only.json -ll
rc=$?
accept_findings "bandit" "$rc" "reports/bandit-only.json"
exit $?
