#!/usr/bin/env bash
# Trivy -- alternative tool, branch PY-107 (Python 3.10, uv_build / poetry).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="src"
PKG="orderlab"

require_python_floor "trivy" "" ""
require_binary "trivy" "trivy"
require_import "trivy" "" ""


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
trivy fs --scanners vuln --format json --output reports/trivy.json .
rc=$?
accept_findings "trivy" "$rc" "reports/trivy.json"
exit $?
