#!/usr/bin/env bash
# Semgrep OSS -- primary tool, branch PY-017 (Python 3.6, poetry-core / pip).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="src"
PKG="orderlab"

require_python_floor "semgrep" ">=3.10" "semgrep==1.176.0"
require_import "semgrep" "semgrep" "semgrep==1.176.0"

mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
"$PYBIN" -m semgrep scan --config p/python --config p/security-audit --json -o reports/semgrep.json "$SRC" && "$PYBIN" -m bandit -r "$SRC" -f json -o reports/bandit.json
rc=$?
accept_findings "semgrep" "$rc" "reports/semgrep.json"
exit $?
