#!/usr/bin/env bash
# testmon -- primary tool, branch PY-047 (Python 3.7, poetry-core / conda).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="src"
PKG="orderlab"

require_python_floor "testmon" ">=3.10" "pytest-testmon==2.2.0"
require_import "testmon" "testmon" "pytest-testmon==2.2.0"

mkdir -p "$ROOT/reports"
cd "$ROOT"

"$PYBIN" -m pytest --testmon -q
rc=$?
accept_findings "testmon" "$rc" "reports/testmon.txt"
exit $?
