#!/usr/bin/env bash
# diff-cover -- alternative tool, branch PY-030 (Python 3.7, setuptools / uv).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "diff-cover" ">=3.10" "diff-cover==10.5.1"
require_import "diff-cover" "diff_cover" "diff-cover==10.5.1"

mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
"$PYBIN" -m diff_cover.diff_cover_tool reports/coverage.xml --compare-branch=HEAD~5 --json-report reports/diff-cover.json
rc=$?
accept_findings "diff-cover" "$rc" "reports/diff-cover.json"
exit $?
