#!/usr/bin/env bash
# SlipCover -- alternative tool, branch PY-103 (Python 3.10, setuptools / conda).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="src"
PKG="orderlab"

require_python_floor "slipcover" ">=3.9" "slipcover==1.1.0"
require_import "slipcover" "slipcover" "slipcover==1.1.0"
require_smoke "slipcover" "slipcover==1.1.0" "$PYBIN" -m slipcover --help


mkdir -p "$ROOT/reports"
cd "$ROOT"

"$PYBIN" -m slipcover --source "$SRC/$PKG" --xml --out reports/slipcover.xml -m pytest -q
rc=$?
accept_findings "slipcover" "$rc" "reports/slipcover.xml"
exit $?
