#!/usr/bin/env bash
# Pymcdc -- primary tool, branch PY-096 (Python 3.9, poetry-core / conda).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "pymcdc" ">=3.10" "pymcdc==0.2.6"
require_import "pymcdc" "pymcdc" "pymcdc==0.2.6"


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
"$PYBIN" -m pymcdc "$SRC/$PKG/analysis/complexity_sample.py" 2>&1 | tee reports/pymcdc.txt
rc=$?
accept_findings "pymcdc" "$rc" "reports/pymcdc.txt"
exit $?
