#!/usr/bin/env bash
# Ruff -- alternative tool, branch PY-026 (Python 3.7, setuptools / pip).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "ruff" ">=3.7" "ruff==0.16.5"
require_import "ruff" "ruff" "ruff==0.16.5"

mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
"$PYBIN" -m ruff check --config "Tool Triggering (Synthetic Data)/ruff/ruff.toml" --output-format json --output-file reports/ruff.json . ; "$PYBIN" -m ruff check --config "Tool Triggering (Synthetic Data)/ruff/ruff.toml" .
rc=$?
accept_findings "ruff" "$rc" "reports/ruff.json"
exit $?
