#!/usr/bin/env bash
# pyan3 + astroid -- alternative tool, branch PY-012 (Python 3.6, uv_build / poetry).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "pyan3" ">=3.10" "pyan3==2.8.1"
require_import "pyan3" "pyan" "pyan3==2.8.1"

mkdir -p "$ROOT/reports"
cd "$ROOT"

"$PYBIN" -m pyan "$SRC/$PKG"/**/*.py --uses --defines --colored --grouped --dot --file reports/pyan3.dot
rc=$?
accept_findings "pyan3" "$rc" "reports/pyan3.dot"
exit $?
