#!/usr/bin/env bash
# symilar (pylint) -- alternative tool, branch PY-143 (Python 3.11, poetry-core / conda).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="src"
PKG="orderlab"

require_python_floor "symilar" ">=3.10" "pylint==4.0.8"
require_import "symilar" "pylint" "pylint==4.0.8"


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
FINDINGS_RC_MAX=31   # this tool's exit code is a bitmask, not a status
"$PYBIN" -m pylint.checkers.symilar --duplicates=25 --ignore-comments $(find "$SRC/$PKG/services" -name "*.py") 2>&1 | tee reports/symilar.txt
rc=$?
accept_findings "symilar" "$rc" "reports/symilar.txt"
exit $?
