#!/usr/bin/env bash
# symilar (pylint) -- alternative tool, branch PY-052 (Python 3.8, setuptools / poetry).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "symilar" ">=3.10" "pylint==4.0.8"
require_import "symilar" "pylint" "pylint==4.0.8"


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
"$PYBIN" -m pylint.checkers.symilar --duplicates=25 --ignore-comments $(find "$SRC/$PKG/services" -name "*.py")
rc=$?
accept_findings "symilar" "$rc" "reports/symilar.txt"
exit $?
