#!/usr/bin/env bash
# Opengrep (taint mode) -- alternative tool, branch PY-214 (Python 3.14, poetry-core / uv).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "opengrep-taint" "" ""
require_binary "opengrep-taint" "opengrep"
require_import "opengrep-taint" "" ""


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
opengrep scan --config "Tool Triggering (Synthetic Data)/opengrep-taint/taint-rules.yaml" --json -o reports/opengrep-taint.json "$SRC"
rc=$?
accept_findings "opengrep-taint" "$rc" "reports/opengrep-taint.json"
exit $?
