#!/usr/bin/env bash
# pylint + vulture -- alternative tool, branch PY-197 (Python 3.14, setuptools / uv).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="src"
PKG="orderlab"

require_python_floor "vulture" ">=3.9" "vulture==2.16"
require_import "vulture" "vulture" "vulture==2.16"
require_smoke "vulture" "vulture==2.16" "$PYBIN" -m vulture --version


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
FINDINGS_RC="3"   # this tool's own findings exit code(s), which collide with the corpus's
"$PYBIN" -m vulture "$SRC/$PKG" "Tool Triggering (Synthetic Data)/vulture/whitelist.py" --min-confidence 60 2>&1 | tee reports/vulture.txt
rc=$?
accept_findings "vulture" "$rc" "reports/vulture.txt"
exit $?
