#!/usr/bin/env bash
# pylint + vulture -- alternative tool, branch PY-002 (Python 3.6, setuptools / pip).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "vulture" ">=3.9" "vulture==2.16"
require_import "vulture" "vulture" "vulture==2.16"

mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
"$PYBIN" -m vulture "$SRC/$PKG" "Tool Triggering (Synthetic Data)/vulture/whitelist.py" --min-confidence 60
rc=$?
accept_findings "vulture" "$rc" "reports/vulture.txt"
exit $?
