#!/usr/bin/env bash
# Lizard -- primary tool, branch PY-148 (Python 3.12, setuptools / poetry).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "lizard" "" "lizard==1.24.0"
require_import "lizard" "lizard" "lizard==1.24.0"
require_smoke "lizard" "lizard==1.24.0" "$PYBIN" -m lizard --version


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
"$PYBIN" -m lizard "$SRC/$PKG" --csv > reports/lizard.csv && "$PYBIN" -m lizard "$SRC/$PKG"
rc=$?
accept_findings "lizard" "$rc" "reports/lizard.csv"
exit $?
