#!/usr/bin/env bash
# pip-audit -- primary tool, branch PY-096 (Python 3.9, poetry-core / conda).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "pip-audit" ">=3.10" "pip-audit==2.10.1"
require_import "pip-audit" "pip_audit" "pip-audit==2.10.1"
require_smoke "pip-audit" "pip-audit==2.10.1" "$PYBIN" -m pip_audit --version


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
"$PYBIN" -m pip_audit -r requirements-runtime.txt -f json -o reports/pip-audit.json --progress-spinner off
rc=$?
accept_findings "pip-audit" "$rc" "reports/pip-audit.json"
exit $?
