#!/usr/bin/env bash
# CrossHair -- primary tool, branch PY-114 (Python 3.10, poetry-core / pip).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "crosshair" ">=3.8" "crosshair-tool==0.0.110"
require_import "crosshair" "crosshair" "crosshair-tool==0.0.110"
require_smoke "crosshair" "crosshair-tool==0.0.110" "$PYBIN" -m crosshair --help


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
"$PYBIN" -m crosshair check "$SRC/$PKG/services/pricing_rules.py" --report_all 2>&1 | tee reports/crosshair.txt
rc=$?
accept_findings "crosshair" "$rc" "reports/crosshair.txt"
exit $?
