#!/usr/bin/env bash
# cosmic-ray -- primary tool, branch PY-097 (Python 3.10, setuptools / pip).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="src"
PKG="orderlab"

require_python_floor "cosmic-ray" ">=3.9" "cosmic-ray==8.7.0"
require_import "cosmic-ray" "cosmic_ray" "cosmic-ray==8.7.0"
require_smoke "cosmic-ray" "cosmic-ray==8.7.0" "$PYBIN_DIR/cosmic-ray" --help


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
rm -f reports/cosmic-ray.sqlite && "$PYBIN_DIR/cosmic-ray" init "Tool Triggering (Synthetic Data)/cosmic-ray/cosmic-ray.toml" reports/cosmic-ray.sqlite && "$PYBIN_DIR/cosmic-ray" exec "Tool Triggering (Synthetic Data)/cosmic-ray/cosmic-ray.toml" reports/cosmic-ray.sqlite && "$PYBIN_DIR/cr-report" reports/cosmic-ray.sqlite
rc=$?
accept_findings "cosmic-ray" "$rc" "reports/cosmic-ray.sqlite"
exit $?
