#!/usr/bin/env bash
# Radon -- primary tool, branch PY-021 (Python 3.6, poetry-core / uv).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="src"
PKG="orderlab"

require_python_floor "radon" "" "radon==6.0.1"
require_import "radon" "radon" "radon==6.0.1"

mkdir -p "$ROOT/reports"
cd "$ROOT"

"$PYBIN" -m radon cc -s -j "$SRC/$PKG" > reports/radon-cc.json && "$PYBIN" -m radon mi -j "$SRC/$PKG" > reports/radon-mi.json && "$PYBIN" -m radon cc -s "$SRC/$PKG/analysis/complexity_sample.py"
rc=$?
accept_findings "radon" "$rc" "reports/radon-cc.json"
exit $?
