#!/usr/bin/env bash
# pylint -- primary tool, branch PY-101 (Python 3.10, setuptools / uv).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="src"
PKG="orderlab"

require_python_floor "pylint" ">=3.10" "pylint==4.0.8"
require_import "pylint" "pylint" "pylint==4.0.8"
require_smoke "pylint" "pylint==4.0.8" "$PYBIN" -m pylint --version


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
FINDINGS_RC_MAX=31   # this tool's exit code is a bitmask, not a status
"$PYBIN" -m pylint --rcfile="Tool Triggering (Synthetic Data)/pylint/pylintrc" "$SRC/$PKG" --output-format=json:reports/pylint.json,colorized
rc=$?
accept_findings "pylint" "$rc" "reports/pylint.json"
exit $?
