#!/usr/bin/env bash
# jscpd -- primary tool, branch PY-174 (Python 3.13, setuptools / uv).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "jscpd" "" "jscpd@5.1.1"
require_binary "jscpd" "npx"
require_import "jscpd" "" "jscpd@5.1.1"


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
npx --yes jscpd@5.1.1 --config "Tool Triggering (Synthetic Data)/jscpd/.jscpd.json" .
rc=$?
accept_findings "jscpd" "$rc" "reports/jscpd/jscpd-report.json"
exit $?
