#!/usr/bin/env bash
# complexipy -- alternative tool, branch PY-036 (Python 3.7, uv_build / poetry).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "complexipy" ">=3.8" "complexipy==7.0.1"
require_import "complexipy" "complexipy" "complexipy==7.0.1"

mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
"$PYBIN" -m complexipy "$SRC/$PKG" -mx 15 -o
rc=$?
accept_findings "complexipy" "$rc" "reports/complexipy.json"
exit $?
