#!/usr/bin/env bash
# complexipy -- alternative tool, branch PY-150 (Python 3.12, setuptools / uv).
# Generated by _generator/runners.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

SRC="packages/domain/src"
PKG="orderlab"

require_python_floor "complexipy" ">=3.8" "complexipy==8.0.0"
require_import "complexipy" "complexipy" "complexipy==8.0.0"
require_smoke "complexipy" "complexipy==8.0.0" "$PYBIN_DIR/complexipy" --version


mkdir -p "$ROOT/reports"
cd "$ROOT"

FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
"$PYBIN_DIR/complexipy" "$SRC/$PKG" --max-complexity-allowed 15 --output reports/complexipy.json --output-format json
rc=$?
accept_findings "complexipy" "$rc" "reports/complexipy.json"
exit $?
